Dev extension interface
usc-isi-i2/sand pull request #11
Opened 2023-06-02 08:33 UTC by punith300i

Refactored the code structure, enabled extension_interfaces and extensions to SAND code base. 

- The extension interfaces are part of the extension_interface module. (assistant, search, export)
- The previous SAND plugins are now considered as extensions and are part of the extension module. (assistant, search, export, wikidata)
- **drepr** exports are part of export extension, added an output format parameter to export the relational data to different format specifications. 
- Added Search interface template with required functions, which will be later extended to wiki data elastic search.

I have tested functionality of the extensions after refactoring the code, screenshots of the tests are given below. 

**Mtab Assistant Prediction API Test**
<img width="1402" alt="Screenshot 2023-06-02 at 1 24 58 AM" src="https://github.com/usc-isi-i2/sand/assets/32421081/d8becd9f-71ca-45d9-9c65-c8fd782ed6a4">

**Export Data API Test**
<img width="500" alt="Screenshot 2023-06-02 at 1 22 20 AM" src="https://github.com/usc-isi-i2/sand/assets/32421081/449b3bcf-a5da-46c2-88e7-3cb809cf98ff">

**Export Model API Test**
<img width="500" alt="Screenshot 2023-06-02 at 1 21 48 AM" src="https://github.com/usc-isi-i2/sand/assets/32421081/c31379d6-77b8-42b8-a981-45f8fab78eca">

2023-06-02 19:00 UTC, binh-vu requested changes

2023-06-02 21:21 UTC, punith300i commented on sand/extension_interface/export.py
> +        """Search Class using name"""
Updated the docs of the function

2023-06-02 21:24 UTC, punith300i commented on sand/controllers/table.py
> +    content = DreprExport().export_data(table, rows, sm.data, OutputFormat.TTL)
Fixed this by adding a config for export and generalised the usage of IExport implementations.

2023-06-03 02:16 UTC, binh-vu approved these changes

2023-06-03 02:17 UTC, merged